name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run type check
        run: bun run type-check

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bunx jest

      - name: Run tests with coverage
        if: matrix.node-version == '20.x'
        run: bunx jest --coverage

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build library
        run: bun run build

      - name: Check build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found"
            exit 1
          fi
          if [ ! -f "dist/index.js" ]; then
            echo "Error: dist/index.js not found"
            exit 1
          fi
          if [ ! -f "dist/index.d.ts" ]; then
            echo "Error: dist/index.d.ts not found"
            exit 1
          fi
          echo "Build output verified successfully"

  integration:
    name: Integration Test
    needs: [lint, type-check, test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build library
        run: bun run build

      - name: Test package installation
        run: |
          # Create a test project
          mkdir -p /tmp/test-project
          cd /tmp/test-project
          
          # Initialize package.json
          echo '{"name": "test-project", "type": "module"}' > package.json
          
          # Install the built package
          bun add file:$GITHUB_WORKSPACE
          
          # Create a test file that imports the library
          cat > test.js << 'EOF'
          import { Button } from '@buun_group/brutalist-ui';
          console.log('Import successful:', typeof Button === 'function');
          
          // Test CSS import
          try {
            // This should not throw an error
            await import('@buun_group/brutalist-ui/styles');
            console.log('CSS import successful');
          } catch (error) {
            console.error('CSS import failed:', error.message);
          }
          EOF
          
          # Try to run the test
          bun test.js